# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - head_controller
    - body_controller
    - left_arm_controller
    - right_arm_controller
    - gripper_controller
    - hand_J1_controller
    - hand_J2_controller
    - hand_J3_controller
    - hand_J4_controller
    - hand_J5_controller
    - hand_J6_controller

  head_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - H-J1
      - H-J2
  body_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - J1
      - Body
  left_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - L-J1
      - L-J2
      - L-J3
      - L-J4
      - L-J5
      - L-J6
      - L-J7
  right_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - R-J1
      - R-J2
      - R-J3
      - R-J4
      - R-J5
      - R-J6
      - R-J7
  gripper_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - gripper_joint
  hand_J1_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - hand_joint1
  hand_J2_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - hand_joint2
  hand_J3_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - hand_joint3
  hand_J4_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - hand_joint4
  hand_J5_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - hand_joint5
  hand_J6_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - hand_joint6