# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - left_arm_controller
    - right_Arm_controller
    - head_controller
    - body_controller

  left_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - L-J1
      - L-J2
      - L-J3
      - L-J4
      - L-J5
      - L-J6
      - L-J7
  right_Arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - R-J1
      - R-J2
      - R-J3
      - R-J4
      - R-J5
      - R-J6
      - R-J7
  head_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - H-J1
      - H-J2
  body_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - J1
      - Body