# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    left_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    right_Arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    head_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    body_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

left_arm_controller:
  ros__parameters:
    joints:
      - L-J1
      - L-J2
      - L-J3
      - L-J4
      - L-J5
      - L-J6
      - L-J7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
right_Arm_controller:
  ros__parameters:
    joints:
      - R-J1
      - R-J2
      - R-J3
      - R-J4
      - R-J5
      - R-J6
      - R-J7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
head_controller:
  ros__parameters:
    joints:
      - H-J1
      - H-J2
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
body_controller:
  ros__parameters:
    joints:
      - J1
      - Body
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity