# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    head_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    body_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    right_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    left_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    hand_J1_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    hand_J2_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    hand_J3_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    hand_J4_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    hand_J5_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    hand_J6_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

head_controller:
  ros__parameters:
    joints:
      - H-J1
      - H-J2
    command_interfaces:
      - position
    state_interfaces:
      - position
body_controller:
  ros__parameters:
    joint: B0
    command_interfaces:
      - position
    state_interfaces:
      - position
right_arm_controller:
  ros__parameters:
    joints:
      - R-J1
      - R-J2
      - R-J3
      - R-J4
      - R-J5
      - R-J6
      - R-J7
    command_interfaces:
      - position
    state_interfaces:
      - position
left_arm_controller:
  ros__parameters:
    joints:
      - L-J1
      - L-J2
      - L-J3
      - L-J4
      - L-J5
      - L-J6
      - L-J7
    command_interfaces:
      - position
    state_interfaces:
      - position
hand_J1_controller:
  ros__parameters:
    joint: hand_joint1
    command_interfaces:
      - position
    state_interfaces:
      - position
hand_J2_controller:
  ros__parameters:
    joint: hand_joint2
    command_interfaces:
      - position
    state_interfaces:
      - position
hand_J3_controller:
  ros__parameters:
    joint: hand_joint3
    command_interfaces:
      - position
    state_interfaces:
      - position
hand_J4_controller:
  ros__parameters:
    joint: hand_joint4
    command_interfaces:
      - position
    state_interfaces:
      - position
hand_J5_controller:
  ros__parameters:
    joint: hand_joint5
    command_interfaces:
      - position
    state_interfaces:
      - position
hand_J6_controller:
  ros__parameters:
    joint: hand_joint6
    command_interfaces:
      - position
    state_interfaces:
      - position
gripper_controller:
  ros__parameters:
    joint: gripper_joint
    command_interfaces:
      - position
    state_interfaces:
      - position